name: "Build & Release"

on:
  pull_request:
    branches:
      - main
      - master
  push:
    branches:
      - main
      - master
      - develop

jobs:
  build-android:
    name: Build Android APK
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v3

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.5'
          channel: 'stable'
          architecture: x64

      - run: flutter pub get

      - run: flutter build apk --release --split-per-abi

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v3
        with:
          name: apk-release
          path: build\app\outputs\apk\release\*.apk

  build-ios:
    name: Build iOS IPA
    runs-on: macos-latest

    if: github.event_name == 'push'  # Only on push, not PR

    steps:
      - uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.5'
          channel: 'stable'

      - run: flutter pub get

      - run: |
          flutter build ios --no-codesign
          cd build/ios/iphoneos
          mkdir Payload
          ln -s ../Runner.app Payload/Runner.app
          zip -r app.ipa Payload

      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ipa-release
          path: build/ios/iphoneos/app.ipa
