name: Flutter CI/CD
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-2022

    env:
      JAVA_HOME: C:\Program Files\Java\jdk-17
      FLUTTER_VERSION: 3.3.5

    steps:
      # Step 1: Checkout project
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Install Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}

      # Step 3: Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Step 4: Analyze code
      - name: Analyze code
        run: flutter analyze

      # Step 5: Run tests
      - name: Run unit tests
        run: flutter test

      # Step 6: Build APK (release mode)
      - name: Build APK
        run: flutter build apk --release

      # Step 7: Archive APK as artifact
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v3
        with:
          name: flutter-apk
          path: build\app\outputs\flutter-apk\app-release.apk
