name: "Build & Release"

on:
  pull_request:
    branches:
      - main
      - master
  push:
    branches:
      - main
      - master
      - develop

jobs:
  build:
    name: Build & Release
    runs-on: windows-2022   # Closest option to Windows 11 Pro

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.5'
          channel: 'stable'
          architecture: x64

      - name: Install dependencies
        run: flutter pub get

      - name: Build Android APK
        run: flutter build apk --release --split-per-abi

      - name: Build iOS IPA (without codesigning)
        if: github.event_name == 'push'  # Only build IPA on push (since PRs won’t support iOS build)
        run: |
          flutter build ios --no-codesign
          cd build/ios/iphoneos
          mkdir Payload
          ln -s ../Runner.app Payload/Runner.app
          zip -r app.ipa Payload

      - name: Push artifacts to GitHub Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: |
            build\app\outputs\apk\release\*.apk,
            build\ios\iphoneos\app.ipa
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.TOKEN }}
