name: "Android Build & Release"

on:
  pull_request:
    branches:
      - main
      - master
  push:
    branches:
      - main
      - master
      - develop

jobs:
  build-android:
    name: Build Android APK
    runs-on: windows-2022

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.5'
          channel: 'stable'
          architecture: x64

      - name: Install dependencies
        run: flutter pub get

      - name: Build Android APK (Release)
        run: flutter build apk --release --split-per-abi

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4   # Updated to v4
        with:
          name: apk-release
          path: build\app\outputs\apk\release\*.apk
